###############################################################################
## eureka 配置
#eureka:
#  client: # 客户端注册进eureka服务器列表
#    service-url:
##      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://10.13.4.56:8761/eureka
#  instance:
##    instance-id: springcloud-instance-provider-dept-8001 # 自定义服务名称信息, 在使用feign的时候,如果和spring.application.name对不上则不起作用
#    prefer-ip-address: true # 访问路径可以显示IP地址

###############################################################################
## H2 DATABASE 数据库配置(用于自测)
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 200

# MYSQL DATABASE 数据库配置application
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.13.4.22:3306/lljr
    username: root
    password: oracle
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

###############################################################################
## redis 配置
  redis:
    host: 10.13.4.30
    port: 6379
    password: IXYtJKtWrZnYTtoa
    database: 0
    pool.max-active: 8
    pool.max-wait: 6000
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 0
#    pool:
#      max-active: 50
#      max-idle: 5
#      min-idle: 0
#      max-wait: 10000ms

###############################################################################
## mongodb 配置
  data:
    mongodb:
      uri: mongodb://10.13.4.42:27017/dev-lanmao
#      username: p2pmongo
#      password: K4sUhvvv2P-59nG
#      authentication-database: wechat



###############################################################################
## mybatis 配置
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
#  type-aliases-package: com.lljr.sms.entity
#  mapper-locations: classpath:mybatis/mapper/**/*.xml

#mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lljr.sms.entity
#  typeEnumsPackage: com.lljr.loan.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false




###############################################################################
# eureka 上节点信息的配置
info:
  app.name: ${spring.application.name}
  company.name: lljr
  build.artifactId: $project.artifactId$
  build.version: $project.version$

###############################################################################
## 日志配置
logging:
#  path: /usr/local/data/logs/
  file: /usr/local/data/logs/${spring.application.name}.log
  level: info

###############################################################################
## 自定义配置

app:
  inner:
    host: 10.13.4.31
    port: 8080
    password: ESJPUYgWQDE4RXlRy91RYXcpdJEwQUHi
    sms-uri: p2p-inner/sms/sendSms
    queue-name: mgm:support:queue
#    callback-url: http://172.29.64.250/clientlib/universal/receivedMsg
#       swagger http://growth-api.dev.bkjk.cn/clientlib/swagger-ui.html
#       swagger http://growth-api.dev.bkjk.cn/clientlib/swagger-ui.html
#       swagger http://172.29.64.250/clientlib/swagger-ui.html