spring:
  profiles:
    active:
    - dev

server:
  port: 8201
spring:
  profiles: uat
  application:
    name: p2p-middleground-sms
eureka:
  client:
    service-url:
      defaultZone: localhost://7001/eureka/
