spring:
  profiles:
    active: prod

server:
  port: 8201
spring:
  profiles: dev
  application:
    name: p2p-middleground-sms
eureka:
  client:
    service-url:
      defaultZone: localhost://7001/eureka/
